// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjI2wtZ4cEbA29SYutMRZteLMYoo02gVE',
    appId: '1:503928826320:android:3758d60632573cc0a0f1d5',
    messagingSenderId: '503928826320',
    projectId: 'qaabl-mobile-dev',
    storageBucket: 'qaabl-mobile-dev.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHILkz5xplHZcCgIWmEl4Vy6_bUmuel4s',
    appId: '1:503928826320:ios:953f60390db392c7a0f1d5',
    messagingSenderId: '503928826320',
    projectId: 'qaabl-mobile-dev',
    storageBucket: 'qaabl-mobile-dev.appspot.com',
    androidClientId: '503928826320-un15kb3kcn4dmrolgeodhurcjgbspmsc.apps.googleusercontent.com',
    iosClientId: '503928826320-eoba3uml5valie6ur5emu0q3dq8l8mhb.apps.googleusercontent.com',
    iosBundleId: 'com.example.qaablMobile',
  );
}
